use_frameworks!
platform :ios, '14.0'

target 'Example' do
    pod 'Record360SDK', :git => 'git@github.com:Record360/ios.git', :branch => '4.23.6-SDK-Release'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
